import { componentTest } from './utils'

describe('dentry components test', () => {
  componentTest('Address', () => {})
  componentTest('Calendar', () => {})
  componentTest('CalendarCard', () => {})
  componentTest('Cascader', () => {})
  componentTest('Checkbox', () => {})
  componentTest('DatePicker', () => {})
  componentTest('Form', () => {})
  componentTest('Input', () => {})
  componentTest('InputNumber', () => {})
  componentTest('Menu', () => {})
  componentTest('NumberKeyboard', () => {})
  componentTest('Picker', () => {})
  componentTest('Radio', () => {})
  componentTest('Range', () => {})
  componentTest('Rate', () => {})
  componentTest('SearchBar', () => {})
  componentTest('ShortPassword', () => {})
  componentTest('Signature', () => {})
  componentTest('Switch', () => {})
  componentTest('TextArea', () => {})
  componentTest('Uploader', () => {})
})
