import { componentTest } from './utils'

describe('feedback components test', () => {
  componentTest('ActionSheet', () => {})
  componentTest('Badge', () => {})
  componentTest('Dialog', () => {})
  componentTest('Drag', () => {})
  componentTest('Empty', () => {})
  componentTest('ResultPage', () => {})
  componentTest('InfiniteLoading', () => {})
  componentTest('Loading', () => {})
  componentTest('NoticeBar', () => {})
  componentTest('Notify', () => {})
  componentTest('Popover', () => {})
  componentTest('Popup', () => {})
  componentTest('PullToRefresh', () => {})
  componentTest('Skeleton', () => {})
  componentTest('Swipe', () => {})
  componentTest('Toast', () => {})
})
