name: CI

on:
  push:
    branches:
      - next
      - V3.0

  pull_request:
    branches:
      - next
      - V3.0

  workflow_dispatch:

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Determine label
        id: determine_label
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "next" ]]; then
            echo "label=2.x" >> $GITHUB_ENV
          elif [[ "${{ github.event.pull_request.base.ref }}" == "V3.0" ]]; then
            echo "label=3.x" >> $GITHUB_ENV
          fi

      - name: Add label to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.label }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: npm run test

      - name: Upload coverage reports to Codecov
        if: ${{ always() }}
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build NutUI-React
        run: npm run build

      - name: Build NutUI-React-Taro
        run: npm run build:taro

      - name: Build NutUI-React Demo
        run: npm run build:site

      - name: Build NutUI-React Taro H5 Demo
        if: github.ref == 'refs/heads/next'
        run: npm run build:taro:site
