name: E2E Tests

on:
  push:
    branches:
      - V3.0
  pull_request:
    branches:
      - V3.0

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run E2E Tests for H5
        env:
          CI: true
        run: pnpm e2e:run:h5

      - name: Run E2E Tests for Taro
        env:
          CI: true
        run: pnpm e2e:run:taro
